<?php
// Automatisch gegenereerd op: 2026-08-01 11:30:14
$arrLang_ = [
    'title' => 'Welkom op ons platform',
    'title_url' => 'gromPil saas',
    'description' => 'Snel, veilig en volledig gebouwd met de modernste technieken van Bootstrap en PHP backend-architectuur.',
    'home' => 'Home',
    'services' => 'Diensten',
    'about_us' => 'Over Ons',
    'contact' => 'Contact',
    'cookie_accept' => 'Accepteren',
    'cookie_all' => 'Alles Accepteren',
    'cookie_decline' => 'Weigeren',
    'cookie_essential' => 'Alleen Essentieel',
    'cookie_functional' => 'Functioneel',
    'cookie_more_info' => 'Meer informatie',
    'cookie_settings' => 'Cookie-instellingen',
    'cookie_text' => 'We gebruiken cookies om uw ervaring te verbeteren. Door verder te gaan, gaat u akkoord met ons gebruik van cookies.',
    'cookie_title' => 'Cookies',
    'bootstrap' => 'Snel, veilig en volledig gebouwd met de modernste technieken van Bootstrap en PHP backend-architectuur.',
    'feature_cookie_text' => 'Eenvoudig instemmen of weigeren via onze geïntegreerde consent-functionaliteit.',
    'feature_cookie_title' => 'Cookie Beheer',
    'feature_security_text' => 'Optimale databeveiliging dankzij ingebouwde CSRF-bescherming en HttpOnly cookies.',
    'feature_security_title' => 'Beveiliging',
    'feature_speed_text' => 'Geoptimaliseerde code zorgt voor bliksemsnelle laadtijden op elk mobiel apparaat.',
    'feature_speed_title' => 'Snelheid',
    'more_info' => 'Meer informatie',
    'start' => 'Aan de slag',
    'welcome' => 'Welkom op ons platform',
    'contact_email' => 'info@grompil.com',
    'cookie_reset' => 'Reset Cookie Keuzes',
    'missing_translation' => 'Ontbrekende vertalingen',
    'gromPilSaas_alt' => 'GrompilSaaS beeld',
];
