<?php
// Automatisch gegenereerd op: 2026-08-01 11:30:14
$arrLang_ = [
    'title' => 'Welcome to our platform',
    'title_url' => 'gromPil saas',
    'description' => 'Fast, secure, and fully built using modern Bootstrap techniques and a PHP backend architecture.',
    'home' => 'Home',
    'services' => 'Services',
    'about_us' => 'About Us',
    'contact' => 'Contact',
    'cookie_accept' => 'Accept',
    'cookie_all' => 'Accept All',
    'cookie_decline' => 'Decline',
    'cookie_essential' => 'Essential Only',
    'cookie_functional' => 'Functional',
    'cookie_more_info' => 'More information',
    'cookie_settings' => 'Cookie settings',
    'cookie_text' => 'We use cookies to improve your experience. By continuing, you agree to our use of cookies.',
    'cookie_title' => 'Cookies',
    'bootstrap' => 'Fast, secure, and fully built using modern Bootstrap techniques and a PHP backend architecture.',
    'feature_cookie_text' => 'Easily give consent or decline through our integrated consent functionality.',
    'feature_cookie_title' => 'Cookie Management',
    'feature_security_text' => 'Optimal data security thanks to built-in CSRF protection and HttpOnly cookies.',
    'feature_security_title' => 'Security',
    'feature_speed_text' => 'Optimized code ensures lightning-fast loading times on any mobile device.',
    'feature_speed_title' => 'Speed',
    'more_info' => 'More information',
    'start' => 'Get started',
    'welcome' => 'Welcome to our platform',
    'contact_email' => 'info@grompil.com',
    'cookie_reset' => 'Reset Cookie Choices',
    'missing_translation' => 'Missing translations',
    'gromPilSaas_alt' => 'GrompilSaaS image',
];
